### ISSUE TITLE
Why is the acc different from the MVGRL paper?

### ISSUE THREAD

**Issue by hcmdgh** [GRAND-Lab/MERIT#3]
Hello! In your paper, your acc of MVGRL method on three datasets (Cora, CiteSeer, PubMed) are 82.9, 72.6, 79.4. But in MVGRL paper, the acc are 86.8, 73.3, 80.1. I think both of you use the same dataset, so could you please explain the reason?

**Comment by KimMeen** [comment]
Hi @hcmdgh, we followed the settings and results in this paper: [Contrastive and Generative Graph Convolutional Networks for Graph-based Semi-Supervised Learning](https://arxiv.org/abs/2009.07111). You may also refer to this page for more details: https://github.com/kavehhassani/mvgrl/issues/7
